server:
  port: 0
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:h2:mem:testDB
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
       ddl-auto: create
    show-sql: true
    open-in-view: false 
  boot:
    admin:
      client:
        url:
        - http://localhost:8800
  cloud:
    config:
      uri:
      - http://localhost:9090
      enabled: false
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
logging:
  file:
    name: user-service.log